// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// nChoosek
unsigned nChoosek(unsigned n, unsigned k);
RcppExport SEXP _robber_nChoosek(SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned >::type n(nSEXP);
    Rcpp::traits::input_parameter< unsigned >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(nChoosek(n, k));
    return rcpp_result_gen;
END_RCPP
}
// var_auc_unif_lbm_cpp
double var_auc_unif_lbm_cpp(NumericMatrix con, NumericVector pi, NumericVector rho, int nr, int nc);
RcppExport SEXP _robber_var_auc_unif_lbm_cpp(SEXP conSEXP, SEXP piSEXP, SEXP rhoSEXP, SEXP nrSEXP, SEXP ncSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type con(conSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pi(piSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< int >::type nc(ncSEXP);
    rcpp_result_gen = Rcpp::wrap(var_auc_unif_lbm_cpp(con, pi, rho, nr, nc));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_robber_nChoosek", (DL_FUNC) &_robber_nChoosek, 2},
    {"_robber_var_auc_unif_lbm_cpp", (DL_FUNC) &_robber_var_auc_unif_lbm_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_robber(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
