# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nChoosek <- function(n, k) {
    .Call(`_robber_nChoosek`, n, k)
}

var_auc_unif_lbm_cpp <- function(con, pi, rho, nr, nc) {
    .Call(`_robber_var_auc_unif_lbm_cpp`, con, pi, rho, nr, nc)
}

